version: '3.8'
services:
  emby:
    image: emby/embyserver
    container_name: emby
    ports:
      - "${EMBY_PORT}:8096"
    volumes:
      - ${MEDIA_PATH}:/media
      - ${CONFIG_PATH}/emby:/config
    restart: always

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    volumes:
      - ${CONFIG_PATH}/jackett:/config
    restart: always

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ${MEDIA_PATH}:/media
      - ${CONFIG_PATH}/sonarr:/config
    restart: always

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - ${MEDIA_PATH}:/media
      - ${CONFIG_PATH}/radarr:/config
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - "${QBITTORRENT_PORT}:8080"
    volumes:
      - ${DOWNLOAD_PATH}:/downloads
      - ${CONFIG_PATH}/qbittorrent:/config
    restart: always
