---
version: "3.0"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    hostname: portainer
    ports:
      - 9000:9000
    volumes: 
      - /Users/joshkoopman/Desktop/portainer/port_app/data:/data

  portainer_agent:
    image: portainer/agent:latest
    container_name: agent-p
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes